import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function hexToAndroid(hex: string): string {
  return `0xFF${hex.slice(1).toUpperCase()}`;
}

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;

  const colorsXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Android colors.xml — generated by ChromaBrew -->
<resources>
  <!-- Brand -->
  <color name="color_primary">${hexToAndroid(light.primary)}</color>
  <color name="color_secondary">${hexToAndroid(light.secondary)}</color>
  <color name="color_accent">${hexToAndroid(light.accent)}</color>
  <color name="color_success">${hexToAndroid(light.success)}</color>
  <color name="color_warning">${hexToAndroid(light.warning)}</color>
  <color name="color_danger">${hexToAndroid(light.danger)}</color>
  <color name="color_info">${hexToAndroid(light.info)}</color>

  <!-- Surfaces -->
  <color name="background">${hexToAndroid(light.background)}</color>
  <color name="surface">${hexToAndroid(light.surface)}</color>
  <color name="foreground">${hexToAndroid(light.foreground)}</color>
  <color name="foreground_muted">${hexToAndroid(light["foreground-muted"])}</color>
  <color name="border">${hexToAndroid(light.border)}</color>

  <!-- Brand Scale -->
${primitives.colors.scale.map((s) => `  <color name="brand_${s.step}">${hexToAndroid(s.hex)}</color>`).join("\n")}
</resources>`;

  const darkColorsXml = `<?xml version="1.0" encoding="utf-8"?>
<!-- Android dark colors.xml — generated by ChromaBrew -->
<resources>
  <color name="color_primary">${hexToAndroid(dark.primary)}</color>
  <color name="color_secondary">${hexToAndroid(dark.secondary)}</color>
  <color name="color_accent">${hexToAndroid(dark.accent)}</color>
  <color name="color_success">${hexToAndroid(dark.success)}</color>
  <color name="color_warning">${hexToAndroid(dark.warning)}</color>
  <color name="color_danger">${hexToAndroid(dark.danger)}</color>
  <color name="color_info">${hexToAndroid(dark.info)}</color>
  <color name="background">${hexToAndroid(dark.background)}</color>
  <color name="surface">${hexToAndroid(dark.surface)}</color>
  <color name="foreground">${hexToAndroid(dark.foreground)}</color>
  <color name="foreground_muted">${hexToAndroid(dark["foreground-muted"])}</color>
  <color name="border">${hexToAndroid(dark.border)}</color>
</resources>`;

  const themeKt = `// Kotlin theme helper — generated by ChromaBrew
// Usage:
//   import ChromaBrewTheme.*
//   surfaceColor = MaterialTheme.colorScheme.primary

package com.chromabrew.theme

import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

object Colors {
  val primary = Color(${hexToAndroid(light.primary)})
  val secondary = Color(${hexToAndroid(light.secondary)})
  val accent = Color(${hexToAndroid(light.accent)})
  val success = Color(${hexToAndroid(light.success)})
  val warning = Color(${hexToAndroid(light.warning)})
  val danger = Color(${hexToAndroid(light.danger)})
  val info = Color(${hexToAndroid(light.info)})
  val background = Color(${hexToAndroid(light.background)})
  val surface = Color(${hexToAndroid(light.surface)})
  val foreground = Color(${hexToAndroid(light.foreground)})
  val foregroundMuted = Color(${hexToAndroid(light["foreground-muted"])})
  val border = Color(${hexToAndroid(light.border)})
}

object DarkColors {
  val primary = Color(${hexToAndroid(dark.primary)})
  val secondary = Color(${hexToAndroid(dark.secondary)})
  val accent = Color(${hexToAndroid(dark.accent)})
  val success = Color(${hexToAndroid(dark.success)})
  val warning = Color(${hexToAndroid(dark.warning)})
  val danger = Color(${hexToAndroid(dark.danger)})
  val info = Color(${hexToAndroid(dark.info)})
  val background = Color(${hexToAndroid(dark.background)})
  val surface = Color(${hexToAndroid(dark.surface)})
  val foreground = Color(${hexToAndroid(dark.foreground)})
  val foregroundMuted = Color(${hexToAndroid(dark["foreground-muted"])})
  val border = Color(${hexToAndroid(dark.border)})
}

val lightColorScheme = lightColorScheme(
  primary = Colors.primary,
  secondary = Colors.secondary,
  tertiary = Colors.accent,
  background = Colors.background,
  surface = Colors.surface,
  onBackground = Colors.foreground,
  onSurface = Colors.foreground,
  error = Colors.danger,
)

val darkColorScheme = darkColorScheme(
  primary = DarkColors.primary,
  secondary = DarkColors.secondary,
  tertiary = DarkColors.accent,
  background = DarkColors.background,
  surface = DarkColors.surface,
  onBackground = DarkColors.foreground,
  onSurface = DarkColors.foreground,
  error = DarkColors.danger,
)

val Typography = Typography(
  displayLarge = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize["5xl"].size)}.sp, fontWeight = FontWeight.Bold),
  displayMedium = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize["4xl"].size)}.sp, fontWeight = FontWeight.Bold),
  headlineLarge = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize["3xl"].size)}.sp, fontWeight = FontWeight.SemiBold),
  headlineMedium = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize["2xl"].size)}.sp, fontWeight = FontWeight.SemiBold),
  titleLarge = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize.xl.size)}.sp, fontWeight = FontWeight.SemiBold),
  bodyLarge = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize.base.size)}.sp),
  bodyMedium = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize.sm.size)}.sp),
  labelSmall = TextStyle(fontSize = ${parseInt(primitives.typography.fontSize.xs.size)}.sp, fontWeight = FontWeight.Medium),
)
`;

  return `// ─── colors.xml (res/values/) ───
${colorsXml}

// ─── colors.xml (res/values-night/) ───
${darkColorsXml}

// ─── Compose theme (ChromaBrewTheme.kt) ───
${themeKt}`;
}

export const androidAdapter: ExportAdapter = {
  id: "android",
  name: "Android XML + Compose",
  description: "XML colors.xml for both themes + Jetpack Compose Material 3 theme",
  generate: (system) => ({
    code: generate(system),
    language: "xml",
    suggestedFilename: "chromabrew-android.xml",
  }),
};
