import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const sans = primitives.typography.fontFamily.sans;
  const fs = primitives.typography.fontSize;

  return `// Ant Design 5 theme — generated by ChromaBrew
// Usage:
//   import { ConfigProvider } from 'antd';
//   import { theme } from './antd-theme';
//   <ConfigProvider theme={theme}><App /></ConfigProvider>

import { theme as antdTheme, type ThemeConfig } from 'antd';

const shared = {
  token: {
    fontFamily: ${JSON.stringify(sans)},
    fontSize: ${parseInt(fs.base.size)},
    borderRadius: ${parseInt(system.primitives.radius.md)},
    colorPrimary: '${light.primary}',
    colorSuccess: '${light.success}',
    colorWarning: '${light.warning}',
    colorError: '${light.danger}',
    colorInfo: '${light.info}',
  },
  components: {
    Button: {
      borderRadius: ${parseInt(system.primitives.radius.md)},
    },
    Card: {
      borderRadiusLG: ${parseInt(system.primitives.radius.lg)},
    },
    Input: {
      borderRadius: ${parseInt(system.primitives.radius.md)},
    },
  },
};

export const lightTheme: ThemeConfig = {
  ...shared,
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    ...shared.token,
    colorBgBase: '${light.background}',
    colorBgContainer: '${light.surface}',
    colorBgElevated: '${light.surface}',
    colorText: '${light.foreground}',
    colorTextSecondary: '${light["foreground-muted"]}',
    colorBorder: '${light.border}',
    colorBorderSecondary: '${light["border-muted"]}',
  },
};

export const darkTheme: ThemeConfig = {
  ...shared,
  algorithm: antdTheme.darkAlgorithm,
  token: {
    ...shared.token,
    colorPrimary: '${dark.primary}',
    colorSuccess: '${dark.success}',
    colorWarning: '${dark.warning}',
    colorError: '${dark.danger}',
    colorInfo: '${dark.info}',
    colorBgBase: '${dark.background}',
    colorBgContainer: '${dark.surface}',
    colorBgElevated: '${dark.surface}',
    colorText: '${dark.foreground}',
    colorTextSecondary: '${dark["foreground-muted"]}',
    colorBorder: '${dark.border}',
    colorBorderSecondary: '${dark["border-muted"]}',
  },
};

export const theme = lightTheme;
`;
}

export const antdAdapter: ExportAdapter = {
  id: "antd",
  name: "Ant Design",
  description: "Ant Design 5 ConfigProvider theme with light and dark algorithms",
  generate: (system) => ({
    code: generate(system),
    language: "typescript",
    suggestedFilename: "antd-theme.ts",
  }),
};
