import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function hexToRgb(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `${r}, ${g}, ${b}`;
}

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const scale = primitives.colors.scale;

  return `/* Bootstrap 5.3+ compatible theme — generated by ChromaBrew */
/* Import after Bootstrap: import 'bootstrap/scss/bootstrap.scss'; */
/* Then add this file: import 'bootstrap-theme.scss'; */

:root {
  /* ── Brand ── */
  --bs-primary: ${light.primary};
  --bs-primary-rgb: ${hexToRgb(light.primary)};
  --bs-secondary: ${light.secondary};
  --bs-secondary-rgb: ${hexToRgb(light.secondary)};
  --bs-success: ${light.success};
  --bs-success-rgb: ${hexToRgb(light.success)};
  --bs-info: ${light.info};
  --bs-info-rgb: ${hexToRgb(light.info)};
  --bs-warning: ${light.warning};
  --bs-warning-rgb: ${hexToRgb(light.warning)};
  --bs-danger: ${light.danger};
  --bs-danger-rgb: ${hexToRgb(light.danger)};

  /* ── Surfaces ── */
  --bs-body-bg: ${light.background};
  --bs-body-color: ${light.foreground};
  --bs-tertiary-bg: ${light.surface};
  --bs-border-color: ${light.border};

  /* ── Scales as custom properties ── */
  ${scale.map((s) => `--bs-scale-${s.step}: ${s.hex};`).join("\n  ")}

  /* ── Typography ── */
  --bs-font-sans: ${primitives.typography.fontFamily.sans};
  --bs-font-mono: ${primitives.typography.fontFamily.mono};
  --bs-body-font-size: ${primitives.typography.fontSize.sm.size};
  --bs-body-line-height: 1.5;
}

.dark,
[data-bs-theme="dark"] {
  --bs-primary: ${dark.primary};
  --bs-primary-rgb: ${hexToRgb(dark.primary)};
  --bs-secondary: ${dark.secondary};
  --bs-secondary-rgb: ${hexToRgb(dark.secondary)};
  --bs-success: ${dark.success};
  --bs-success-rgb: ${hexToRgb(dark.success)};
  --bs-info: ${dark.info};
  --bs-info-rgb: ${hexToRgb(dark.info)};
  --bs-warning: ${dark.warning};
  --bs-warning-rgb: ${hexToRgb(dark.warning)};
  --bs-danger: ${dark.danger};
  --bs-danger-rgb: ${hexToRgb(dark.danger)};

  --bs-body-bg: ${dark.background};
  --bs-body-color: ${dark.foreground};
  --bs-tertiary-bg: ${dark.surface};
  --bs-border-color: ${dark.border};
}

/* ── Bootstrap component overrides ── */
.btn-primary {
  --bs-btn-bg: var(--bs-primary);
  --bs-btn-border-color: var(--bs-primary);
  --bs-btn-hover-bg: color-mix(in srgb, var(--bs-primary) 85%, black);
  --bs-btn-hover-border-color: color-mix(in srgb, var(--bs-primary) 85%, black);
}

.btn-secondary {
  --bs-btn-bg: var(--bs-secondary);
  --bs-btn-border-color: var(--bs-secondary);
}

.card {
  --bs-card-bg: var(--bs-tertiary-bg);
  --bs-card-border-color: var(--bs-border-color);
}

.navbar {
  --bs-navbar-bg: var(--bs-tertiary-bg);
}

.alert-success { --bs-alert-bg: ${light.success}15; }
.alert-danger  { --bs-alert-bg: ${light.danger}15; }
.alert-warning { --bs-alert-bg: ${light.warning}15; }
.alert-info    { --bs-alert-bg: ${light.info}15; }
`;
}

export const bootstrapAdapter: ExportAdapter = {
  id: "bootstrap",
  name: "Bootstrap 5.3",
  description: "CSS custom properties compatible with Bootstrap 5.3+",
  generate: (system) => ({
    code: generate(system),
    language: "css",
    suggestedFilename: "bootstrap-theme.scss",
  }),
};
