import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const sans = primitives.typography.fontFamily.sans;
  const mono = primitives.typography.fontFamily.mono;
  const fs = primitives.typography.fontSize;

  return `// Chakra UI v2+ theme — generated by ChromaBrew
// Usage:
//   import { ChakraProvider, extendTheme } from '@chakra-ui/react';
//   import { theme } from './chakra-theme';
//   <ChakraProvider theme={theme}><App /></ChakraProvider>

import { extendTheme, type ThemeConfig } from '@chakra-ui/react';

const config: ThemeConfig = {
  initialColorMode: 'light',
  useSystemColorMode: false,
};

export const theme = extendTheme({
  config,
  fonts: {
    heading: ${JSON.stringify(sans)},
    body: ${JSON.stringify(sans)},
    mono: ${JSON.stringify(mono)},
  },
  fontSizes: {
    xs: '${fs.xs.size}',
    sm: '${fs.sm.size}',
    md: '${fs.base.size}',
    lg: '${fs.lg.size}',
    xl: '${fs.xl.size}',
    '2xl': '${fs["2xl"].size}',
    '3xl': '${fs["3xl"].size}',
    '4xl': '${fs["4xl"].size}',
    '5xl': '${fs["5xl"].size}',
  },
  radii: {
    sm: '${primitives.radius.sm}',
    md: '${primitives.radius.md}',
    lg: '${primitives.radius.lg}',
    xl: '${primitives.radius.xl}',
    full: '${primitives.radius.full}',
  },
  colors: {
    brand: {
      50: '${primitives.colors.scale[0]?.hex}',
      100: '${primitives.colors.scale[1]?.hex}',
      200: '${primitives.colors.scale[2]?.hex}',
      300: '${primitives.colors.scale[3]?.hex}',
      400: '${primitives.colors.scale[4]?.hex}',
      500: '${primitives.colors.scale[5]?.hex}',
      600: '${primitives.colors.scale[6]?.hex}',
      700: '${primitives.colors.scale[7]?.hex}',
      800: '${primitives.colors.scale[8]?.hex}',
      900: '${primitives.colors.scale[9]?.hex}',
      950: '${primitives.colors.scale[10]?.hex}',
    },
    success: { 500: '${light.success}' },
    warning: { 500: '${light.warning}' },
    error: { 500: '${light.danger}' },
    info: { 500: '${light.info}' },
    bg: {
      DEFAULT: '${light.background}',
      _dark: '${dark.background}',
    },
    surface: {
      DEFAULT: '${light.surface}',
      _dark: '${dark.surface}',
    },
    foreground: {
      DEFAULT: '${light.foreground}',
      _dark: '${dark.foreground}',
    },
    muted: {
      DEFAULT: '${light["foreground-muted"]}',
      _dark: '${dark["foreground-muted"]}',
    },
    border: {
      DEFAULT: '${light.border}',
      _dark: '${dark.border}',
    },
  },
  styles: {
    global: {
      body: {
        bg: '${light.background}',
        color: '${light.foreground}',
      },
    },
  },
});
`;
}

export const chakraAdapter: ExportAdapter = {
  id: "chakra",
  name: "Chakra UI",
  description: "Chakra UI v2 extendTheme with tokens, radii, and dark mode",
  generate: (system) => ({
    code: generate(system),
    language: "typescript",
    suggestedFilename: "chakra-theme.ts",
  }),
};
