import { formatOklch, hexToRgb, rgbToOklch } from "../colour/convert";
import { semanticTokenIds } from "../tokens/generate";
import type { DesignSystem, ThemeMode, ThemeTokens } from "../types";
import type { ExportAdapter } from "./adapter";

/** Shared token grouping used by CSS-family exports. */
export const TOKEN_GROUPS: Array<{ title: string; tokens: string[] }> = [
  { title: "Page", tokens: ["background", "background-subtle", "foreground", "foreground-muted", "foreground-subtle"] },
  { title: "Surfaces", tokens: ["surface", "surface-raised", "surface-muted"] },
  { title: "Primary & secondary", tokens: ["primary", "primary-hover", "primary-active", "primary-foreground", "secondary", "secondary-hover", "secondary-foreground"] },
  { title: "Accent", tokens: ["accent", "accent-foreground"] },
  { title: "Borders & inputs", tokens: ["border", "border-muted", "border-strong", "input", "input-border", "focus-ring"] },
  { title: "Status", tokens: ["success", "success-foreground", "warning", "warning-foreground", "danger", "danger-foreground", "info", "info-foreground"] },
];

export function toOklchString(hex: string): string {
  return formatOklch(rgbToOklch(hexToRgb(hex)));
}

function block(selector: string, tokens: ThemeTokens): string {
  const lines: string[] = [`${selector} {`];
  for (const group of TOKEN_GROUPS) {
    for (const id of group.tokens) {
      if (!(id in tokens)) continue;
      lines.push(`  --${id}: ${tokens[id as keyof ThemeTokens]};`);
    }
  }
  lines.push("}");
  return lines.join("\n");
}

export const cssAdapter: ExportAdapter = {
  id: "css",
  name: "CSS Variables",
  description: "Plain CSS custom properties with a .dark override block.",
  generate(system: DesignSystem) {
    const header = `/*\n  ${system.metadata.name} design tokens\n  Source: ${system.source.primary.hex}\n  Generated by Colorsmith — free design system generator\n*/\n`;
    const light = block(":root", system.themes.light);
    const dark = block(".dark", system.themes.dark);
    return {
      code: `${header}${light}\n\n${dark}\n`,
      language: "css",
      suggestedFilename: "design-tokens.css",
    };
  },
};

/**
 * Emit every semantic token for one mode as `[id]: value` entries.
 * Used by adapters that need raw maps (JSON etc.).
 */
export function themeEntries(
  system: DesignSystem,
  mode: ThemeMode,
): Array<[string, string]> {
  const tokens = system.themes[mode];
  return semanticTokenIds()
    .filter((id) => id in tokens)
    .map((id) => [id, tokens[id]] as [string, string]);
}
