import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const fs = primitives.typography.fontSize;

  const token = (name: string, value: string) => `"${name}": "${value}"`;
  const colourTokens: string[] = [];

  // Semantic colours
  const semanticPairs: [string, string, string][] = [
    ["background", light.background, dark.background],
    ["surface", light.surface, dark.surface],
    ["foreground", light.foreground, dark.foreground],
    ["foreground-muted", light["foreground-muted"], dark["foreground-muted"]],
    ["primary", light.primary, dark.primary],
    ["secondary", light.secondary, dark.secondary],
    ["accent", light.accent, dark.accent],
    ["border", light.border, dark.border],
    ["success", light.success, dark.success],
    ["warning", light.warning, dark.warning],
    ["danger", light.danger, dark.danger],
    ["info", light.info, dark.info],
  ];

  for (const [name, lightVal, darkVal] of semanticPairs) {
    colourTokens.push(`      ${token(`color.${name}`, lightVal)},`);
    colourTokens.push(`      ${token(`color.${name}.dark`, darkVal)},`);
  }

  // Brand scale
  primitives.colors.scale.forEach((s) => {
    colourTokens.push(`      ${token(`color.brand.${s.step}`, s.hex)},`);
  });

  return `{
  "chromabrew": {
    "version": "1.0",
    "description": "Design tokens for Figma Tokens Studio — generated by ChromaBrew"
  },
  "color": {
    ${colourTokens.join("\n")}
  },
  "fontSize": {
      ${token("xs", fs.xs.size)},
      ${token("sm", fs.sm.size)},
      ${token("base", fs.base.size)},
      ${token("lg", fs.lg.size)},
      ${token("xl", fs.xl.size)},
      ${token("2xl", fs["2xl"].size)},
      ${token("3xl", fs["3xl"].size)},
      ${token("4xl", fs["4xl"].size)},
      ${token("5xl", fs["5xl"].size)}
  },
  "fontFamily": {
      ${token("sans", primitives.typography.fontFamily.sans)},
      ${token("mono", primitives.typography.fontFamily.mono)}
  },
  "borderRadius": {
      ${token("sm", primitives.radius.sm)},
      ${token("md", primitives.radius.md)},
      ${token("lg", primitives.radius.lg)},
      ${token("xl", primitives.radius.xl)},
      ${token("full", primitives.radius.full)}
  },
  "spacing": {
      ${Object.entries(primitives.spacing)
        .map(([k, v]) => token(k, v))
        .join(",\n      ")}
  }
}`;
}

export const figmaAdapter: ExportAdapter = {
  id: "figma",
  name: "Figma Tokens",
  description: "Tokens Studio JSON format — paste directly into Figma Tokens plugin",
  generate: (system) => ({
    code: generate(system),
    language: "json",
    suggestedFilename: "figma-tokens.json",
  }),
};
