import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const fs = primitives.typography.fontSize;

  return `// Flutter theme — generated by ChromaBrew
// Usage:
//   import 'chromabrew_theme.dart';
//   MaterialApp(theme: lightTheme, darkTheme: darkTheme);

import 'package:flutter/material.dart';

class ChromaBrewColors {
  ChromaBrewColors._();

  // Brand
  static const primary = Color(0xFF${light.primary.slice(1)});
  static const secondary = Color(0xFF${light.secondary.slice(1)});
  static const accent = Color(0xFF${light.accent.slice(1)});
  static const success = Color(0xFF${light.success.slice(1)});
  static const warning = Color(0xFF${light.warning.slice(1)});
  static const danger = Color(0xFF${light.danger.slice(1)});
  static const info = Color(0xFF${light.info.slice(1)});

  // Surfaces
  static const background = Color(0xFF${light.background.slice(1)});
  static const surface = Color(0xFF${light.surface.slice(1)});
  static const foreground = Color(0xFF${light.foreground.slice(1)});
  static const foregroundMuted = Color(0xFF${light["foreground-muted"].slice(1)});
  static const border = Color(0xFF${light.border.slice(1)});
}

class ChromaBrewDarkColors {
  ChromaBrewDarkColors._();

  static const primary = Color(0xFF${dark.primary.slice(1)});
  static const secondary = Color(0xFF${dark.secondary.slice(1)});
  static const accent = Color(0xFF${dark.accent.slice(1)});
  static const success = Color(0xFF${dark.success.slice(1)});
  static const warning = Color(0xFF${dark.warning.slice(1)});
  static const danger = Color(0xFF${dark.danger.slice(1)});
  static const info = Color(0xFF${dark.info.slice(1)});
  static const background = Color(0xFF${dark.background.slice(1)});
  static const surface = Color(0xFF${dark.surface.slice(1)});
  static const foreground = Color(0xFF${dark.foreground.slice(1)});
  static const foregroundMuted = Color(0xFF${dark["foreground-muted"].slice(1)});
  static const border = Color(0xFF${dark.border.slice(1)});
}

class ChromaBrewTypography {
  ChromaBrewTypography._();

  static const String fontFamily = '${primitives.typography.fontFamily.sans}';
  static const String monoFontFamily = '${primitives.typography.fontFamily.mono}';

  static const TextStyle displayLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs["5xl"].size},
    fontWeight: FontWeight.w700,
  );

  static const TextStyle displayMedium = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs["4xl"].size},
    fontWeight: FontWeight.w700,
  );

  static const TextStyle headlineLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs["3xl"].size},
    fontWeight: FontWeight.w600,
  );

  static const TextStyle headlineMedium = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs["2xl"].size},
    fontWeight: FontWeight.w600,
  );

  static const TextStyle titleLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs.xl.size},
    fontWeight: FontWeight.w600,
  );

  static const TextStyle bodyLarge = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs.base.size},
    fontWeight: FontWeight.w400,
  );

  static const TextStyle bodyMedium = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs.sm.size},
    fontWeight: FontWeight.w400,
  );

  static const TextStyle labelSmall = TextStyle(
    fontFamily: fontFamily,
    fontSize: ${fs.xs.size},
    fontWeight: FontWeight.w500,
  );
}

ThemeData get lightTheme => ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  colorScheme: ColorScheme.light(
    primary: ChromaBrewColors.primary,
    secondary: ChromaBrewColors.secondary,
    error: ChromaBrewColors.danger,
    surface: ChromaBrewColors.surface,
    onSurface: ChromaBrewColors.foreground,
  ),
  scaffoldBackgroundColor: ChromaBrewColors.background,
  textTheme: const TextTheme(
    displayLarge: ChromaBrewTypography.displayLarge,
    displayMedium: ChromaBrewTypography.displayMedium,
    headlineLarge: ChromaBrewTypography.headlineLarge,
    headlineMedium: ChromaBrewTypography.headlineMedium,
    titleLarge: ChromaBrewTypography.titleLarge,
    bodyLarge: ChromaBrewTypography.bodyLarge,
    bodyMedium: ChromaBrewTypography.bodyMedium,
    labelSmall: ChromaBrewTypography.labelSmall,
  ),
);

ThemeData get darkTheme => ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: ColorScheme.dark(
    primary: ChromaBrewDarkColors.primary,
    secondary: ChromaBrewDarkColors.secondary,
    error: ChromaBrewDarkColors.danger,
    surface: ChromaBrewDarkColors.surface,
    onSurface: ChromaBrewDarkColors.foreground,
  ),
  scaffoldBackgroundColor: ChromaBrewDarkColors.background,
  textTheme: const TextTheme(
    displayLarge: ChromaBrewTypography.displayLarge,
    displayMedium: ChromaBrewTypography.displayMedium,
    headlineLarge: ChromaBrewTypography.headlineLarge,
    headlineMedium: ChromaBrewTypography.headlineMedium,
    titleLarge: ChromaBrewTypography.titleLarge,
    bodyLarge: ChromaBrewTypography.bodyLarge,
    bodyMedium: ChromaBrewTypography.bodyMedium,
    labelSmall: ChromaBrewTypography.labelSmall,
  ),
);
`;
}

export const flutterAdapter: ExportAdapter = {
  id: "flutter",
  name: "Flutter / Dart",
  description: "Material 3 ThemeData with colors, typography, and light/dark themes",
  generate: (system) => ({
    code: generate(system),
    language: "dart",
    suggestedFilename: "chromabrew_theme.dart",
  }),
};
