import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function hexToUIColor(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return `UIColor(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)}, alpha: 1.0)`;
}

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const fs = primitives.typography.fontSize;

  return `// iOS Swift theme — generated by ChromaBrew
// Usage:
//   import ChromaBrewTheme
//   let colors = Theme.colors

import SwiftUI

public enum Theme {

  // MARK: - Light Mode Colors

  public enum Light {
    public static let background = ${hexToUIColor(light.background)}
    public static let surface = ${hexToUIColor(light.surface)}
    public static let foreground = ${hexToUIColor(light.foreground)}
    public static let foregroundMuted = ${hexToUIColor(light["foreground-muted"])}
    public static let border = ${hexToUIColor(light.border)}

    public static let primary = ${hexToUIColor(light.primary)}
    public static let secondary = ${hexToUIColor(light.secondary)}
    public static let accent = ${hexToUIColor(light.accent)}
    public static let success = ${hexToUIColor(light.success)}
    public static let warning = ${hexToUIColor(light.warning)}
    public static let danger = ${hexToUIColor(light.danger)}
    public static let info = ${hexToUIColor(light.info)}
  }

  // MARK: - Dark Mode Colors

  public enum Dark {
    public static let background = ${hexToUIColor(dark.background)}
    public static let surface = ${hexToUIColor(dark.surface)}
    public static let foreground = ${hexToUIColor(dark.foreground)}
    public static let foregroundMuted = ${hexToUIColor(dark["foreground-muted"])}
    public static let border = ${hexToUIColor(dark.border)}

    public static let primary = ${hexToUIColor(dark.primary)}
    public static let secondary = ${hexToUIColor(dark.secondary)}
    public static let accent = ${hexToUIColor(dark.accent)}
    public static let success = ${hexToUIColor(dark.success)}
    public static let warning = ${hexToUIColor(dark.warning)}
    public static let danger = ${hexToUIColor(dark.danger)}
    public static let info = ${hexToUIColor(dark.info)}
  }

  // MARK: - Brand Scale

  public enum Brand {
${primitives.colors.scale.map((s) => `    public static let ${s.step} = ${hexToUIColor(s.hex)}`).join("\n")}
  }

  // MARK: - Typography

  public enum Typography {
    public static let displayLarge = Font.system(size: ${fs["5xl"].size}, weight: .bold)
    public static let displayMedium = Font.system(size: ${fs["4xl"].size}, weight: .bold)
    public static let headlineLarge = Font.system(size: ${fs["3xl"].size}, weight: .semibold)
    public static let headlineMedium = Font.system(size: ${fs["2xl"].size}, weight: .semibold)
    public static let titleLarge = Font.system(size: ${fs.xl.size}, weight: .semibold)
    public static let bodyLarge = Font.system(size: ${fs.base.size})
    public static let bodyMedium = Font.system(size: ${fs.sm.size})
    public static let caption = Font.system(size: ${fs.xs.size})
    public static let mono = Font.system(size: ${fs.sm.size}, design: .monospaced)
  }

  // MARK: - Spacing

  public enum Spacing {
${Object.entries(primitives.spacing)
  .map(([k, v]) => `    public static let ${k} = CGFloat(${parseFloat(v) * 16})`)
  .join("\n")}
  }

  // MARK: - Radii

  public enum Radii {
    public static let sm = CGFloat(${parseFloat(primitives.radius.sm) * 16})
    public static let md = CGFloat(${parseFloat(primitives.radius.md) * 16})
    public static let lg = CGFloat(${parseFloat(primitives.radius.lg) * 16})
    public static let xl = CGFloat(${parseFloat(primitives.radius.xl) * 16})
  }

  // MARK: - Semantic colors (adapts to light/dark automatically)

  public static func color(light: UIColor, dark: UIColor) -> Color {
    Color(UITraitCollection { traits in
      traits.userInterfaceStyle == .dark ? dark : light
    })
  }

  public static let background = color(light: Light.background, dark: Dark.background)
  public static let surface = color(light: Light.surface, dark: Dark.surface)
  public static let foreground = color(light: Light.foreground, dark: Dark.foreground)
  public static let primary = color(light: Light.primary, dark: Dark.primary)
  public static let secondary = color(light: Light.secondary, dark: Dark.secondary)
}
`;
}

export const iosAdapter: ExportAdapter = {
  id: "ios-swift",
  name: "iOS Swift",
  description: "SwiftUI Color + Font + spacing constants with light/dark adaptation",
  generate: (system) => ({
    code: generate(system),
    language: "swift",
    suggestedFilename: "ChromaBrewTheme.swift",
  }),
};
