import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

interface DtcgToken {
  $type: "color";
  $value: string;
  $description?: string;
}

/**
 * W3C Design Tokens (DTCG) compatible JSON with primitive scales and both
 * semantic themes.
 */
export const jsonAdapter: ExportAdapter = {
  id: "json",
  name: "JSON Tokens",
  description: "Structured design tokens in DTCG-style JSON.",
  generate(system: DesignSystem) {
    const brand: Record<string, DtcgToken> = {};
    for (const step of system.primitives.colors.scale) {
      brand[String(step.step)] = {
        $type: "color",
        $value: step.hex,
        ...(step.isSource
          ? { $description: "Original source colour" }
          : {}),
      };
    }

    const palette: Record<string, DtcgToken> = {};
    for (const swatch of system.primitives.colors.palette) {
      palette[swatch.role.toLowerCase().replace(/[^a-z0-9]+/g, "-")] = {
        $type: "color",
        $value: swatch.hex,
        $description: `${system.configuration.paletteStrategy} · ${swatch.role}`,
      };
    }

    const themeTokens = (mode: "light" | "dark") => {
      const out: Record<string, DtcgToken> = {};
      for (const [id, hex] of Object.entries(system.themes[mode])) {
        out[id] = { $type: "color", $value: hex };
      }
      return out;
    };

    const payload = {
      $description: `${system.metadata.name} design tokens — generated by Colorsmith from ${system.source.primary.hex}`,
      $generator: {
        name: system.metadata.name,
        version: system.metadata.generatorVersion,
        strategy: system.configuration.paletteStrategy,
      },
      primitive: {
        color: { brand, palette },
      },
      semantic: {
        light: themeTokens("light"),
        dark: themeTokens("dark"),
      },
    };

    return {
      code: JSON.stringify(payload, null, 2),
      language: "json",
      suggestedFilename: "design-tokens.json",
    };
  },
};
