import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

interface DtcgToken {
  $type: "color";
  $value: string;
  $description?: string;
}

/**
 * W3C Design Tokens (DTCG) compatible JSON with primitive scales and both
 * semantic themes.
 */
export const jsonAdapter: ExportAdapter = {
  id: "json",
  name: "JSON Tokens",
  description: "Structured design tokens in DTCG-style JSON.",
  generate(system: DesignSystem) {
    const brand: Record<string, DtcgToken> = {};
    for (const step of system.primitives.colors.scale) {
      brand[String(step.step)] = {
        $type: "color",
        $value: step.hex,
        ...(step.isSource
          ? { $description: "Original source colour" }
          : {}),
      };
    }

    const palette: Record<string, DtcgToken> = {};
    for (const swatch of system.primitives.colors.palette) {
      palette[swatch.role.toLowerCase().replace(/[^a-z0-9]+/g, "-")] = {
        $type: "color",
        $value: swatch.hex,
        $description: `${system.configuration.paletteStrategy} Â· ${swatch.role}`,
      };
    }

    // Layout primitives â€” colour tokens carry DTCG types; composite
    // layout structures use conventional shapes.
    const { typography, spacing, radius, shadows } = system.primitives;

    const fontFamily = {
      sans: { $type: "fontFamily" as const, $value: [typography.fontFamily.sans] },
      mono: { $type: "fontFamily" as const, $value: [typography.fontFamily.mono] },
    };

    const fontSize: Record<string, unknown> = {};
    for (const [name, step] of Object.entries(typography.fontSize)) {
      fontSize[name] = {
        size: { $type: "dimension", $value: step.size },
        "line-height": { $type: "number", $value: step.lineHeight },
        "letter-spacing": { $type: "dimension", $value: step.letterSpacing },
      };
    }

    const spacingTokens: Record<string, { $type: string; $value: string }> = {};
    for (const [key, value] of Object.entries(spacing)) {
      spacingTokens[key] = { $type: "dimension", $value: value };
    }

    const radiusTokens: Record<string, { $type: string; $value: string }> = {};
    for (const [name, value] of Object.entries(radius)) {
      radiusTokens[name] = { $type: "dimension", $value: value };
    }

    const shadowTokens: Record<string, { $type: "shadow"; $value: unknown }> = {};
    for (const [name, cssValue] of Object.entries(shadows)) {
      shadowTokens[name] = {
        $type: "shadow",
        $value: {
          offsetX: parseShadowPart(cssValue, 0),
          offsetY: parseShadowPart(cssValue, 1),
          blur: parseShadowPart(cssValue, 2),
          color: "rgb(0 0 / 1)",
          // Raw CSS preserved for consumers that prefer it.
          css: cssValue,
        },
      };
    }

    const themeTokens = (mode: "light" | "dark") => {
      const out: Record<string, DtcgToken> = {};
      for (const [id, hex] of Object.entries(system.themes[mode])) {
        out[id] = { $type: "color", $value: hex };
      }
      return out;
    };

    const payload = {
      $description: `${system.metadata.name} design tokens â€” generated by ChromaBrew from ${system.source.primary.hex}`,
      $generator: {
        name: system.metadata.name,
        version: system.metadata.generatorVersion,
        strategy: system.configuration.paletteStrategy,
      },
      primitive: {
        color: { brand, palette },
        typography: { fontFamily, fontSize },
        spacing: spacingTokens,
        radius: radiusTokens,
        shadow: shadowTokens,
      },
      semantic: {
        light: themeTokens("light"),
        dark: themeTokens("dark"),
      },
    };

    return {
      code: JSON.stringify(payload, null, 2),
      language: "json",
      suggestedFilename: "design-tokens.json",
    };
  },
};

/** Extract the nth length part of a box-shadow string (px values). */
function parseShadowPart(shadow: string, index: number): { $type: string; $value: string } {
  const parts = shadow.match(/-?[\d.]+(px|rem)/g) ?? [];
  return { $type: "dimension", $value: parts[index] ?? "0px" };
}
