import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const sans = primitives.typography.fontFamily.sans;
  const fs = primitives.typography.fontSize;

  return `// Material UI v5+ theme — generated by ChromaBrew
// Usage:
//   import { createTheme, ThemeProvider } from '@mui/material/styles';
//   import { theme } from './mui-theme';
//   <ThemeProvider theme={theme}><App /></ThemeProvider>

import { createTheme, type ThemeOptions } from '@mui/material/styles';

const shared: ThemeOptions = {
  typography: {
    fontFamily: ${JSON.stringify(sans)},
    h1: { fontSize: '${fs["5xl"].size}' },
    h2: { fontSize: '${fs["4xl"].size}' },
    h3: { fontSize: '${fs["3xl"].size}' },
    h4: { fontSize: '${fs["2xl"].size}' },
    h5: { fontSize: '${fs.xl.size}' },
    h6: { fontSize: '${fs.lg.size}' },
    body1: { fontSize: '${fs.base.size}' },
    body2: { fontSize: '${fs.sm.size}' },
    caption: { fontSize: '${fs.xs.size}' },
  },
  shape: {
    borderRadius: ${parseInt(primitives.radius.md)},
  },
  spacing: 8,
};

export const lightTheme = createTheme({
  ...shared,
  palette: {
    mode: 'light',
    primary: { main: '${light.primary}' },
    secondary: { main: '${light.secondary}' },
    error: { main: '${light.danger}' },
    warning: { main: '${light.warning}' },
    info: { main: '${light.info}' },
    success: { main: '${light.success}' },
    background: {
      default: '${light.background}',
      paper: '${light.surface}',
    },
    text: {
      primary: '${light.foreground}',
      secondary: '${light["foreground-muted"]}',
    },
    divider: '${light.border}',
  },
});

export const darkTheme = createTheme({
  ...shared,
  palette: {
    mode: 'dark',
    primary: { main: '${dark.primary}' },
    secondary: { main: '${dark.secondary}' },
    error: { main: '${dark.danger}' },
    warning: { main: '${dark.warning}' },
    info: { main: '${dark.info}' },
    success: { main: '${dark.success}' },
    background: {
      default: '${dark.background}',
      paper: '${dark.surface}',
    },
    text: {
      primary: '${dark.foreground}',
      secondary: '${dark["foreground-muted"]}',
    },
    divider: '${dark.border}',
  },
});

// Default export uses light theme
export const theme = lightTheme;
`;
}

export const muiAdapter: ExportAdapter = {
  id: "mui",
  name: "Material UI",
  description: "MUI v5+ createTheme with light and dark palettes",
  generate: (system) => ({
    code: generate(system),
    language: "typescript",
    suggestedFilename: "mui-theme.ts",
  }),
};
