import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

type Token = { $type: string; $value: string | Record<string, unknown> };
const colorToken = (value: string): Token => ({ $type: "color", $value: value });

/**
 * Penpot import — Penpot reads design tokens through its Design Tokens
 * feature, which accepts W3C DTCG JSON. This adapter emits a DTCG file
 * shaped so Penpot's colours group maps cleanly to its token library.
 */
export const penpotAdapter: ExportAdapter = {
  id: "penpot",
  name: "Penpot",
  description:
    "DTCG JSON for Penpot's Design Tokens — import via Penpot's Design Tokens plugin.",
  generate(system: DesignSystem) {
    const { primitives } = system;

    const brand: Record<string, Token> = {};
    for (const step of primitives.colors.scale) {
      brand[String(step.step)] = colorToken(step.hex);
    }

    const semantic = (mode: "light" | "dark"): Record<string, Token> => {
      const out: Record<string, Token> = {};
      for (const [id, hex] of Object.entries(system.themes[mode])) {
        out[id] = colorToken(hex);
      }
      return out;
    };

    const spacing: Record<string, Token> = {};
    for (const [k, v] of Object.entries(primitives.spacing)) {
      spacing[k] = { $type: "dimension", $value: v };
    }

    const radius: Record<string, Token> = {};
    for (const [k, v] of Object.entries(primitives.radius)) {
      radius[k] = { $type: "dimension", $value: v };
    }

    const payload = {
      $description: `${system.metadata.name} — Penpot design tokens generated by ChromaBrew. Import in Penpot via Design Tokens > Import.`,
      $extensions: {
        "com.chromabrew": {
          version: system.metadata.generatorVersion,
          source: system.source.primary.hex,
        },
      },
      color: {
        brand,
        "light": semantic("light"),
        "dark": semantic("dark"),
      },
      spacing,
      radius,
    };

    return {
      code: JSON.stringify(payload, null, 2),
      language: "json",
      suggestedFilename: "penpot-tokens.json",
    };
  },
};
