import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

function generate(system: DesignSystem): string {
  const { themes, primitives } = system;
  const light = themes.light;
  const dark = themes.dark;
  const fs = primitives.typography.fontSize;

  return `// React Native theme — generated by ChromaBrew
// Usage:
//   import { lightTheme, darkTheme } from './rn-theme';
//   const theme = isDark ? darkTheme : lightTheme;

import { StyleSheet } from 'react-native';

export const colors = {
  // Brand
  primary: '${light.primary}',
  secondary: '${light.secondary}',
  accent: '${light.accent}',
  success: '${light.success}',
  warning: '${light.warning}',
  danger: '${light.danger}',
  info: '${light.info}',

  // Surfaces
  background: '${light.background}',
  surface: '${light.surface}',
  foreground: '${light.foreground}',
  foregroundMuted: '${light["foreground-muted"]}',
  border: '${light.border}',

  // Brand scale
  brand: {
    50: '${primitives.colors.scale[0]?.hex}',
    100: '${primitives.colors.scale[1]?.hex}',
    200: '${primitives.colors.scale[2]?.hex}',
    300: '${primitives.colors.scale[3]?.hex}',
    400: '${primitives.colors.scale[4]?.hex}',
    500: '${primitives.colors.scale[5]?.hex}',
    600: '${primitives.colors.scale[6]?.hex}',
    700: '${primitives.colors.scale[7]?.hex}',
    800: '${primitives.colors.scale[8]?.hex}',
    900: '${primitives.colors.scale[9]?.hex}',
    950: '${primitives.colors.scale[10]?.hex}',
  },
} as const;

export const darkColors = {
  primary: '${dark.primary}',
  secondary: '${dark.secondary}',
  accent: '${dark.accent}',
  success: '${dark.success}',
  warning: '${dark.warning}',
  danger: '${dark.danger}',
  info: '${dark.info}',
  background: '${dark.background}',
  surface: '${dark.surface}',
  foreground: '${dark.foreground}',
  foregroundMuted: '${dark["foreground-muted"]}',
  border: '${dark.border}',
  brand: {
    50: '${primitives.colors.scale[0]?.hex}',
    100: '${primitives.colors.scale[1]?.hex}',
    200: '${primitives.colors.scale[2]?.hex}',
    300: '${primitives.colors.scale[3]?.hex}',
    400: '${primitives.colors.scale[4]?.hex}',
    500: '${primitives.colors.scale[5]?.hex}',
    600: '${primitives.colors.scale[6]?.hex}',
    700: '${primitives.colors.scale[7]?.hex}',
    800: '${primitives.colors.scale[8]?.hex}',
    900: '${primitives.colors.scale[9]?.hex}',
    950: '${primitives.colors.scale[10]?.hex}',
  },
} as const;

export const typography = StyleSheet.create({
  h1: {
    fontSize: ${parseInt(fs["5xl"].size)},
    fontWeight: '700',
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  h2: {
    fontSize: ${parseInt(fs["4xl"].size)},
    fontWeight: '700',
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  h3: {
    fontSize: ${parseInt(fs["3xl"].size)},
    fontWeight: '600',
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  h4: {
    fontSize: ${parseInt(fs["2xl"].size)},
    fontWeight: '600',
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  body: {
    fontSize: ${parseInt(fs.base.size)},
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  bodySmall: {
    fontSize: ${parseInt(fs.sm.size)},
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  caption: {
    fontSize: ${parseInt(fs.xs.size)},
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.sans)},
  },
  mono: {
    fontSize: ${parseInt(fs.sm.size)},
    fontFamily: ${JSON.stringify(primitives.typography.fontFamily.mono)},
  },
});

export const spacing = ${JSON.stringify(primitives.spacing, null, 2)};

export const radii = {
  sm: ${parseInt(primitives.radius.sm)},
  md: ${parseInt(primitives.radius.md)},
  lg: ${parseInt(primitives.radius.lg)},
  xl: ${parseInt(primitives.radius.xl)},
};

// Light theme stylesheet
export const lightTheme = StyleSheet.create({
  container: { backgroundColor: colors.background, flex: 1 },
  card: { backgroundColor: colors.surface, borderRadius: radii.lg, padding: 16 },
  text: { color: colors.foreground },
  textMuted: { color: colors.foregroundMuted },
  border: { borderColor: colors.border, borderWidth: 1 },
});

// Dark theme stylesheet
export const darkTheme = StyleSheet.create({
  container: { backgroundColor: darkColors.background, flex: 1 },
  card: { backgroundColor: darkColors.surface, borderRadius: radii.lg, padding: 16 },
  text: { color: darkColors.foreground },
  textMuted: { color: darkColors.foregroundMuted },
  border: { borderColor: darkColors.border, borderWidth: 1 },
});
`;
}

export const reactNativeAdapter: ExportAdapter = {
  id: "react-native",
  name: "React Native",
  description: "StyleSheet + color objects with light/dark themes",
  generate: (system) => ({
    code: generate(system),
    language: "typescript",
    suggestedFilename: "rn-theme.ts",
  }),
};
