import type { DesignSystem } from "../types";
import type { ExportAdapter } from "./adapter";

type Token = { $type: string; $value: string | Record<string, unknown> };

function colorToken(value: string, description?: string): Token {
  const t: Token = { $type: "color", $value: value };
  if (description) (t as { $description?: string }).$description = description;
  return t;
}

/**
 * W3C Design Tokens (DTCG) conforming JSON — the community standard for
 * token interchange. Importable by Tokens Studio, Style Dictionary,
 * Penpot and other tools that read the DTCG format.
 */
export const w3cAdapter: ExportAdapter = {
  id: "w3c",
  name: "Design Tokens (W3C)",
  description:
    "W3C DTCG token JSON — import into Tokens Studio, Style Dictionary, Penpot and other DTCG-compatible tools.",
  generate(system: DesignSystem) {
    const { primitives } = system;
    const scale = primitives.colors.scale;

    const brand: Record<string, Token> = {};
    for (const step of scale) {
      brand[String(step.step)] = colorToken(
        step.hex,
        step.isSource ? "Original source colour" : undefined,
      );
    }

    const palette: Record<string, Token> = {};
    for (const swatch of primitives.colors.palette) {
      palette[swatch.role.toLowerCase().replace(/[^a-z0-9]+/g, "-")] =
        colorToken(swatch.hex, `${system.configuration.paletteStrategy} — ${swatch.role}`);
    }

    const semantic = (mode: "light" | "dark"): Record<string, Token> => {
      const out: Record<string, Token> = {};
      for (const [id, hex] of Object.entries(system.themes[mode])) {
        out[id] = colorToken(hex);
      }
      return out;
    };

    const fontSize: Record<string, Record<string, Token>> = {};
    for (const [name, step] of Object.entries(primitives.typography.fontSize)) {
      fontSize[name] = {
        size: { $type: "dimension", $value: step.size },
        "line-height": { $type: "number", $value: String(step.lineHeight) },
        "letter-spacing": { $type: "dimension", $value: step.letterSpacing },
      };
    }

    const spacing: Record<string, Token> = {};
    for (const [k, v] of Object.entries(primitives.spacing)) {
      spacing[k] = { $type: "dimension", $value: v };
    }

    const radius: Record<string, Token> = {};
    for (const [k, v] of Object.entries(primitives.radius)) {
      radius[k] = { $type: "dimension", $value: v };
    }

    const payload = {
      $description: `${system.metadata.name} — W3C Design Tokens generated by ChromaBrew from ${system.source.primary.hex}`,
      $version: "1.0",
      color: {
        brand,
        palette,
        semantic: {
          light: semantic("light"),
          dark: semantic("dark"),
        },
      },
      typography: {
        $type: "typography",
        fontFamily: {
          sans: { $type: "fontFamily", $value: [primitives.typography.fontFamily.sans] },
          mono: { $type: "fontFamily", $value: [primitives.typography.fontFamily.mono] },
        },
        fontSize,
      },
      spacing,
      radius,
    };

    return {
      code: JSON.stringify(payload, null, 2),
      language: "json",
      suggestedFilename: "design-tokens-w3c.json",
    };
  },
};
